#!/bin/bash
source "$DIR_SHARE/ConfLanIs"

if [ "$i_WAN_ipv6" =  "" ];then
SRVipv6linklocal=$(ip addr show $i_WAN_ipv4  | grep inet6 | awk '{print $2}' | grep "fe80" | cut -d"/" -f1)
else
SRVipv6linklocal=$(ip addr show $i_WAN_ipv6  | grep inet6 | awk '{print $2}' | grep "fe80" | cut -d"/" -f1)
fi
##apt-get install rsync openssh-server
genpasswd() {
  local length=${1:-8}
  tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${length} | xargs
}
serversyncon () {
	echo <serversyncon>
	useradd --shell /bin/bash --create-home --system ctsync
	chmod 750 /home/ctsync
	passwordsrv=$(genpasswd)
	echo "ctsync:$passwordsrv" | chpasswd
	rm -rf /home/ctsync/.ssh
	mkdir -p /home/ctsync/.ssh
	{ echo "
Port 22
AddressFamily inet6
ListenAddress fe80::/10

#SyslogFacility AUTH
#LogLevel INFO
StrictModes yes
PubkeyAuthentication yes
AuthorizedKeysFile	.ssh/authorized_keys
PasswordAuthentication yes
PermitEmptyPasswords no
UsePAM yes
AllowAgentForwarding yes
AllowTcpForwarding yes
X11Forwarding no
PrintMotd no
Banner none
AcceptEnv LANG LC_*
# override default of no subsystems
Subsystem	sftp	/usr/lib/openssh/sftp-server"
} > /etc/ssh/sshd_config
service sshd restart

{
echo" # pour activer la syncro avec ce poste lancer les commandes suivante sur les postes de votre réseaux local que vous voulez syncroniser
CTparental -cson $SRVipv6linklocal $passwordsrv
"
} > /root/commande_clients_ctsync.txt
cat /root/commande_clients_ctsync.txt
echo "* */15 * * * root /usr/bin/CTparental -expsync > /dev/null 2>&1" > /etc/cron.d/CTparentalsrv
	echo </serversyncon>
}

clientsyncon () {
	echo "<clientsyncon>"
	useradd --shell /bin/bash --create-home --system ctsync
	chmod 750 /home/ctsync
	password=$(genpasswd)
	echo "ctsync:$password" | chpasswd
	rm -rf /home/ctsync/.ssh
	mkdir -p /home/ctsync/.ssh
	echo "le mots de passe demandée est le suivant:
$passwordsrv
"
	ssh-keygen -t rsa -b 2048 -P "" -f /home/ctsync/.ssh/id_rsa -q
	chown ctsync:ctsync /home/ctsync/.ssh/id_rsa
	chmod 600 /home/ctsync/.ssh/id_rsa
	ssh-copy-id ctsync@$SRVipv6linklocal
	echo "* */15 * * * ctsync  sleep $(/usr/bin/perl -e 'print int(rand(120))') && rsync --delete --chmod 755 -av ctsync@$SRVipv6linklocal:/home/ctsync/confCTparental.tar.gz /home/ctsync/confCTparental.tar.gz > /dev/null 2>&1" > /etc/cron.d/CTparentalclient
	
	echo "</clientsyncon>"
}

clientsync () {
	rsync --chmod 755 -av ctsync@$SRVipv6linklocal:/home/ctsync/confCTparental.tar.gz /home/ctsync/confCTparental.tar.gz.md5
	rsync --chmod 755 -av ctsync@$SRVipv6linklocal:/home/ctsync/confCTparental.tar.gz /home/ctsync/confCTparental.tar.gz
	md5fileorig=$(grep " " "/home/ctsync/confCTparental.tar.gz.md5" | cut -d" " -f1)
	md5filenew=$( md5sum /home/ctsync/confCTparental.tar.gz | cut -d" " -f1 )
	## on sassure que les fichiers sont pas corrompus.
	if [ "$md5fileorig" = "$md5filenew" ]; then
	 if [ -f /home/ctsync/confCTparental.tar.gz.md5.old ];then
		md5fileorig=$(grep " " "/home/ctsync/confCTparental.tar.gz.md5.old" | cut -d" " -f1)
		## on verifie si il y a un changement dans la conf
		if [ "$md5fileorig" = "$md5filenew" ]; then
		FILEimpconf=/home/ctsync/confCTparental.tar.gz
		importconf
		md5sum /home/ctsync/confCTparental.tar.gz > /home/ctsync/confCTparental.tar.gz.md5.old
		fi
	 else
		FILEimpconf=/home/ctsync/confCTparental.tar.gz
		importconf
		md5sum /home/ctsync/confCTparental.tar.gz > /home/ctsync/confCTparental.tar.gz.md5.old
	 fi
	fi

