#!/bin/sh
#exporter la configuration ctparental en exécutant CTparental -exp ./
# puis utilisez ce script pour générer le fichier de zone pour bind9.
# CTparental_bind9 CTparental.conf.yy.mm.dd.tar.gz
# bind9 fonctione très bien mais et extrèmement gourment en ram  ( 3,2 G 
# sous windows 10 amd64)
SED="/bin/sed -i"
echo " génération Blacklist pour dind9"
zonefile=named.conf.ctparental-zones
echo -n > $zonefile
FILEimpconf="${1}"
tar -xvzf "$FILEimpconf" 
mkdir etc/CTparental/blacklist-enabled
while read line
do
cp -f etc/CTparental/dnsfilter-available/$line".conf" etc/CTparental/blacklist-enabled/
done < etc/CTparental/categories-enabled.conf

FILE_tmp=tmpfile
FILE_tmp2=tmpfile2

cat etc/CTparental/blacklist-enabled/* | sed -e "s/ //g" | sed -e "s/address=\///g" | sed -e "s/^\.\{1,10\}//g" | sed -e "s/\/127.0.0.10//g"  | grep -v "#" | sort -u > "$FILE_tmp"

while read line
do
domain=$line
{
	
echo "	zone \"$domain\" {"
echo '	type master;'
echo '	file "/etc/bind/db.ctparental";'
echo '  };'

} >> $FILE_tmp2
done < "$FILE_tmp"

cat "$FILE_tmp2" >> $zonefile 

rm -f $FILE_tmp
rm -f $FILE_tmp2
rm -rf etc/CTparental/
